meta:
  version: v4.0.5
  name: rergo
  author: rdc

units:
  SS: 1.5 # screw size
  FR: 4.1 # feet radius: 3.2mm / 3.8mm for new feet
  CH: 1.5 # case height: 1.5mm
  PH: 1.5 # plate height: 1.5mm
  WH: CH*4.75 # wall height: 7.125mm
  FI: 0.5 # feet indentation: 0.5mm
  SR: 4.6/2 # screw head radius: 4.6/2 = 2.15mm
  SH: 2.2/2 # screw hole radius: 2.2/2 = 1.1mm

points:
  key.padding: cy
  zones:
    main:
      anchor.shift: [150, -150]  # Fix placement on KiCAD sheet
      anchor.rotate: 14
      key.spread: cx
      rows:
        bottom.row_net: P8
        home.row_net: P9
        top.row_net: P2
        numbers.row_net: P3
      columns:
        pinky:
          key.col_net: P18
          rows.bottom.bind: [2, 55, 0.5, 1.5] # u r d l
          rows.home.bind: [2, 0, 0, 1.5] # u r d l
          rows.top.bind: [2, 0, 0, 1.5] # u r d l
          rows.numbers.bind: [0, 15, 0, 1.5] # u r d l
        ring:
          key.col_net: P19
          key.splay: -8
          key.stagger: cy * 0.66
          key.spread: cx * 1.15
          rows.numbers.bind: [0.5, 6, 0, 1.5] # u r d l
        middle:
          key.col_net: P5
          key.splay: -2
          key.stagger: cy * 0.4
          key.spread: cx * 1.15
          rows.bottom.bind: [5, 0, 5, 0] # u r d l
          rows.numbers.bind: [0, 0.5, 0, 0] # u r d l
        index:
          key.col_net: P6
          key.splay: -2
          key.stagger: cy * -0.55
          key.spread: cx * 1.15
          rows.numbers.bind: [2.5, 1, 1, 5] # u r d l
          rows.bottom.bind: [0, 0, 6, 10] # u r d l
        far:
          key.col_net: P7
          key.splay: -3.5
          key.stagger: cy * -0.35
          key.spread: cx * 1.1
          rows.numbers.bind: [0.5, 26, 67, 5] # u r d l
    thumb:
      anchor:
        ref: main_far_bottom
        shift: [cx * -0.5 , cy * -1.25]
        rotate: -4
      rows.single.row_net: P16
      columns:
        inner:
          key.col_net: P15
          key.rotate: 5
          rows.single.bind: [20, 20, 5, 1.5] # u r d l
        home:
          key.col_net: P14
          key.rotate: -10
          key.shift: [cx * 0.35, cy * -0.05]
          rows.single.bind: [9, 0, 0, 20] # u r d l
        outer:
          key.col_net: P10
          key.rotate: -20
          key.shift: [cx * 0.55, cy * -0.45]
          rows.single.bind: [2, 1.5, 2, 20] # u r d l
    screw_1:
      key.tags:
        - helper
        - screws
      anchor:
        aggregate.parts:
          - ref: main_pinky_numbers
          - ref: main_pinky_top
          - ref: main_ring_numbers
          - ref: main_ring_top
    screw_2:
      key.tags:
        - helper
        - screws
      anchor:
        aggregate.parts:
          - ref: main_middle_bottom
        shift: [0, -15]
    screw_3:
      key.tags:
        - helper
        - screws
      anchor:
        aggregate.parts:
          - ref: main_index_numbers
          - ref: main_far_numbers
        shift: [1, 0]
    screw_4:
      key.tags:
        - helper
        - screws
      anchor:
        aggregate.parts:
          - ref: thumb_home_single
          - ref: main_far_bottom
        shift: [10, 5]
outlines:
  _raw:
    - what: rectangle # main key outlines
      size: [cx - 0.5, cy - 0.5]
      bound: true
      where:
        - /main/
        - /thumb/
  cutout:
    - what: outline
      name: _raw
      fillet: 2
  keycaps:
    - what: rectangle
      size: [cx - 0.5, cy - 0.5]
      bound: false
      where:
        - /main/
        - /thumb/
  key_switch_cutout:
    - what: rectangle
      size: [14, 14]
      bound: false
      where:
        - /main/
        - /thumb/
  power_switch:
    - what: rectangle
      size: [4, 6.5]
      where:
        ref: main_far_bottom
        shift: [32.0, 15]
  nicenano_v2:
    - what: rectangle
      size: [18, 33]
      where:
        ref: main_far_home
        shift: [21.5, 24.5]
    - what: rectangle
      size: [9, 2]
      where:
        ref: main_far_home
        shift: [21.5, 42]
  jstph:
    - what: rectangle
      size: [7.6, 6]
      where:
        ref: main_far_bottom
        shift: [16.5, 17.5]
  reset_switch:
    - what: rectangle
      size: [3, 2.5]
      where:
        ref: main_far_bottom
        shift: [32.5, 0]
        rotate: -90
  _screw_heads:
    - what: circle
      where: screws
      radius: SR
  _screw_holes:
    - what: circle
      where: screws
      radius: SH
  _inner_wall:
    - what: outline
      name: _raw
      expand: 0.25
      fillet: 2
  _outer_wall:
    - what: outline
      name: _raw
      expand: 2.25
  feet:
    - what: circle
      radius: FR
      where: main_pinky_numbers
      adjust:
        shift: [cx * -0.25, cy * 0.25]
    - what: circle
      radius: FR
      where: main_pinky_bottom
      adjust:
        shift: [cx * -0.25, cy * -0.25]
    - what: circle
      radius: FR
      where: main_middle_numbers
      adjust:
        shift: [cx * 0.25, cy * 0.25]
    - what: circle
      radius: FR
      where: main_far_top
      adjust:
        shift: [cx * 1.70, cy * 1.25]
    - what: circle
      radius: FR
      where: thumb_inner_single
      adjust:
        shift: [cx * -0.25, cy * -0.5]
    - what: circle
      radius: FR
      where: thumb_outer_single
      adjust:
        shift: [0, 0]
  _tent_raw:
    - what: rectangle
      size: [56, 14.5] # actual size: 55.5 x 14.0
      where: main_far_bottom
      fillet: 2
      adjust:
        shift: [7, -2]
    - what: rectangle
      size: [56, 14.5]
      where: main_far_top
      fillet: 2
      adjust:
        shift: [7, 10]
  tent:
    - what: circle
      radius: FR
      where: main_pinky_numbers
      adjust:
        shift: [cx * -0.25, cy * 0.25]
    - what: circle
      radius: FR
      where: main_pinky_bottom
      adjust:
        shift: [cx * -0.25, cy * -0.25]
    - what: outline
      name: _tent_raw
  lip:
    - what: rectangle
      size: [6.5, 2]
      where:
        ref: main_middle_numbers
        shift: [0, cy * 0.5]
    - what: rectangle
      size: [6.5, 2]
      where:
        ref: main_pinky_numbers
        shift: [0, cy * 0.5]
    - what: rectangle
      size: [6.5, 2]
      where:
        ref: main_far_numbers
        shift: [0, cy * 0.5]
  _components_cutout:
    - what: rectangle
      size: [22, 59.75]
      where:
        ref: main_far_home
        shift: [23.5, 12.15]
    - what: outline
      name: power_switch
      expand: 0.75
      #where:
      #  shift: [2.5, 0]
    - what: outline
      name: reset_switch
      expand: 0.75
  case:
    - what: outline
      name: _inner_wall
      operation: stack
    - what: outline
      name: _outer_wall
      operation: stack
  preview:
    - what: outline
      name: cutout
      operation: stack
    - what: outline
      name: keycaps
      operation: stack
    - what: outline
      name: _screw_heads
      operation: stack
    - what: outline
      name: power_switch
      operation: stack
    - what: outline
      name: nicenano_v2
      operation: stack
    - what: outline
      name: reset_switch
      operation: stack
    - what: outline
      name: jstph
      operation: stack
  case_preview:
    - what: outline
      name: cutout
      operation: stack
    - what: outline
      name: _inner_wall
      operation: stack
    - what: outline
      name: _outer_wall
      operation: stack
    - what: outline
      name: feet
      operation: stack
    - what: outline
      name: lip
      operation: stack
  tent_case_preview:
    - what: outline
      name: cutout
      operation: stack
    - what: outline
      name: _inner_wall
      operation: stack
    - what: outline
      name: _outer_wall
      operation: stack
    - what: outline
      name: tent
      operation: stack
    - what: outline
      name: lip
      operation: stack
  plate_preview:
    - what: outline
      name: cutout
      operation: stack
    - what: outline
      name: key_switch_cutout
      operation: stack
    #- what: outline
    #  name: _screw_heads
    #  operation: stack
    - what: outline
      name: _components_cutout
      operation: stack
  _plate_tester_cutout:
    - what: rectangle
      size: [95, 115]
      where:
        ref: main_index_home
        shift: [-35, -5]
  plate_tester_preview:
    - what: outline
      name: plate_preview
    - what: outline
      name: _plate_tester_cutout
  _tent_tester_cutout:
    - what: rectangle
      size: [95, 120]
      where:
        ref: main_index_home
        shift: [-47, -5]
    - what: rectangle
      size: [130, 60]
      where:
        ref: main_far_bottom
        shift: [0, -20]
  _tent_foot_tester:
    - what: circle
      radius: FR
      where: main_far_home
      adjust:
        shift: [25, 10]
  tent_tester_preview:
    - what: outline
      name: tent_case_preview
    - what: outline
      name: _tent_tester_cutout
    - what: outline
      name: _tent_foot_tester
cases:
  _bottom:
    - name: _inner_wall
      extrude: CH
  _full_wall:
    - name: case
      extrude: WH
  _power_switch_cutout:
    - name: power_switch
      extrude: WH
      shift: [3.5, 0, CH]
  _feet:
    - name: feet
      extrude: CH / 2
  _tent:
    - name: tent
      extrude: CH / 2
  _lip:
    - name: lip
      extrude: 0.5
      shift: [0, 0,WH - 0.5]
  _bottom_feet_case:
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _feet
      operation: subtract
  _bottom_tent_case:
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _tent
      operation: subtract
  _wall:
    - what: case
      name: _full_wall
      operation: add
    - what: case
      name: _power_switch_cutout
      operation: subtract
  bottom_case:
    - what: case
      name: _bottom_feet_case
    - what: case
      name: _wall
    - what: case
      name: _lip
  tent_case:
    - what: case
      name: _bottom_tent_case
    - what: case
      name: _wall
    - what: case
      name: _lip
  _sunk_screw_heads:
    - what: outline
      name: _screw_holes
      extrude: PH - 0.25
      operation: add
    - what: outline
      name: _screw_heads
      extrude: 0.25
      operation: add
      shift: [0, 0, PH - 0.25]
  plate:
    - what: outline
      name: cutout
      extrude: PH
      operation: add
    - what: outline
      name: key_switch_cutout
      extrude: PH
      operation: subtract
    #- what: case
    #  name: _sunk_screw_heads
    #  operation: subtract
    - what: outline
      name: _components_cutout
      extrude: PH
      operation: subtract
  plate_tester:
    - what: case
      name: plate
      operation: add
    - what: outline
      name: _plate_tester_cutout
      operation: subtract
      extrude: PH*5
  tent_tester:
    - what: case
      name: tent_case
      operation: add
    - what: outline
      name: _tent_foot_tester
      operation: subtract
    - what: outline
      name: _tent_tester_cutout
      operation: subtract
      extrude: PH*5
pcbs:
  rergo:
    template: kicad8
    outlines:
      main.outline: cutout
      keycaps:
        outline: keycaps
        layer: Eco1.User
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where:
          - /main/
          - /thumb/
        adjust:
          rotate: 180
        params:
          from: "{{col_net}}"
          to: "{{colrow}}"
          choc_v1_support: false
          include_plated_holes: false
          hotswap: true
          reversible: true
          include_stabilizer_pad: true
          include_corner_marks: true
      diode:
        what: ceoloide/diode_tht_sod123
        where:
          - /main/
          - /thumb/
        adjust:
          shift: [5.8, 0]
          rotate: 180
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          reversible: true
          include_traces_vias: true
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params.reversible: true
        params.reverse_mount: true
        where:
          ref: main_far_home
          shift: [21.5, 24.5]
          rotate: 0
      power:
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
          from: pos
          to: RAW
        where:
          ref: main_far_bottom
          shift: [32.0, 15]
      reset:
        what: rdc/reset_switch_b3u_1000p
        params:
          reversible: true
        where:
          ref: main_far_bottom
          shift: [32.5, 0]
          rotate: -90
      bat:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: main_far_bottom
          shift: [14.5, 17.5]
          rotate: 90
        params:
            reversible: true
            BAT_P: pos
      m2_screws:
        what: ceoloide/mounting_hole_npth
        where: /screws/
        params:
          hole_size: 4.6
          hole_drill: 2.2
      name:
        what: ceoloide/utility_text
        params:
          reversible: true
          face: "SF Mono"
          text: "rergo v4"
          height: 2
          width: 2
          bold: true
        where:
          ref: main_pinky_bottom
          shift: [25, -6]
      logo:
        what: rdc/logo
        params.reversible: true
        params.scale: 1
        where:
          ref: main_far_bottom
          shift: [20, 5]